### ISSUE TITLE
pkgs --upgrade错误

### ISSUE THREAD

**Issue by Faynman** [RT-Thread/rt-thread#1590]
在多台机器测试都发生以下错误:
```
root@e545157deb4d:~/rt-thread/bsp/allwinner_tina# source ~/.env/env.sh
root@e545157deb4d:~/rt-thread/bsp/allwinner_tina# pkgs --upgrade
Traceback (most recent call last):
  File "/root/.env/tools/scripts/env.py", line 31, in <module>
    from cmds import *
  File "/root/.env/tools/scripts/cmds/cmd_package.py", line 32, in <module>
    import requests
ImportError: No module named requests
root@e545157deb4d:~/rt-thread/bsp/allwinner_tina# which pkgs
/root/.env/tools/scripts/pkgs
root@e545157deb4d:~/rt-thread/bsp/allwinner_tina#
```
请问大家这个问题怎么解决?

**Comment by Faynman** [comment]
已解决, 我的ubuntu没有安装requests模块, 通过pip 安装后就能解决.
pip install requests

**Comment by SummerGGift** [comment]
嗯
